#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:D:/PFG_Applications/gwt-2.0.0/gwt-user.jar:D:/PFG_Applications/gwt-2.0.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src au.com.showcase.application.client.Message  ;

