function $b(){}
function hc(){}
function kc(){}
function nc(){}
function pv(){}
function tv(){}
function fd(a,b){a.W(b)}
function Yt(a,b){a.o[TH]=b}
function Xt(a,b){Bs(a.o,UH,b)}
function Zt(a,b){Bs(a.o,VH,b)}
function cd(a,b){return new Jb(a,b)}
function Xb(){this.a=ac(new bc)}
function oc(){oc=eG;cc=new hc}
function pc(){pc=eG;dc=new kc}
function qc(){qc=eG;ec=new nc}
function Jb(a,b){Ib();Q.call(this,a,b)}
function As(a,b,c){tt(a,(bx(),cx(b)),c)}
function kv(a){if(a==_u){return true}return a==cv}
function lv(a){if(a==$u){return true}return a==Zu}
function rv(a){this.b=(ew(),bw).a;this.e=(jw(),iw).a;this.a=a}
function mv(){dv();Uu.call(this);this.b=(ew(),bw);this.c=(jw(),iw);this.e[dI]=0;this.e[eI]=0}
function hv(a,b){var c;c=vl(a.k,32);c.b=b.a;!!c.d&&(c.d[_H]=b.a,undefined)}
function iv(a,b){var c;c=vl(a.k,32);c.e=b.a;!!c.d&&Bs(c.d,aI,b.a)}
function gv(a,b){var c;c=vl(a.k,32);c.c=b;!!c.d&&Bs(c.d,UH,c.c)}
function jv(a,b){var c;c=vl(a.k,32);c.f=b;!!c.d&&Bs(c.d,VH,c.f)}
function rt(a){var b=0,c=a.firstChild;while(c){c.nodeType==1&&++b;c=c.nextSibling}return b}
function qt(a,b){var c=0,d=a.firstChild;while(d){if(d.nodeType==1){if(b==c)return d;++c}d=d.nextSibling}return null}
function tt(a,b,c){var d=0,e=a.firstChild,f=null;while(e){if(e.nodeType==1){if(d==c){f=e;break}++d}e=e.nextSibling}a.insertBefore(b,f)}
function dv(){dv=eG;Yu=new pv;_u=new pv;$u=new pv;Zu=new pv;av=new pv;bv=new pv;cv=new pv}
function ld(a){var b;!a.e&&(a.e=(b=cd((!a.k&&(a.k=new Xk),a.k),(!a.f&&(a.f=new Xb(new $b)),a.f),!a.d&&(a.d=new Qb)),fd(b,(!a.o&&(a.o=new Ly),a.o)),b));return a.e}
function ev(a,b,c){var d;if(c==Yu){if(b==a.a){return}else if(a.a){throw new PB('Only one CENTER widget may be added')}}hu(b);fy(a.f,b);c==Yu&&(a.a=b);d=new rv(c);b.k=d;hv(b,a.b);iv(b,a.c);fv(a);ju(b,a)}
function ac(a){var b,c,d;b=new mv;ev(b,(c=new _v((d=new CC,new Nr(Pg(d.a))).a),c.o[TH]='GGPMPBCDO',c.o.style[UH]='70px',c.o.style[VH]=WH,c),(dv(),av));ev(b,a.b,Yu);jv(a.b,WH);gv(a.b,WH);ev(b,a.c,bv);jv(a.c,WH);gv(a.c,XH);ev(b,a.d,cv);jv(a.d,YH);gv(a.d,WH);b.o[TH]='GGPMPBCDH';b.o.style[UH]=WH;b.o.style[VH]=WH;return b}
function bc(){var a,b,c,d;a=(qc(),ec);mc(a);this.a=(oc(),cc);gc(this.a);this.e=(pc(),dc);jc(this.e);this.b=new _v((b=new CC,new Nr(Pg(b.a))).a);Yt(this.b,'GGPMPBCDG');Xt(this.b,WH);Zt(this.b,WH);this.c=new _v((c=new CC,new Nr(Pg(c.a))).a);Yt(this.c,'GGPMPBCDI');Xt(this.c,XH);Zt(this.c,WH);this.d=new _v((d=new CC,new Nr(Pg(d.a))).a);Yt(this.d,'GGPMPBCDE GGPMPBCDF');Xt(this.d,WH);Zt(this.d,'200px')}
function fv(a){var b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q;b=a.d;while(rt(b)>0){Yg(b,qt(b,0))}n=1;e=1;for(h=new py(a.f);h.a<h.b.c-1;){d=ny(h);f=vl(d.k,32).a;f==av||f==bv?++n:(f==Zu||f==cv||f==_u||f==$u)&&++e}o=ll(Tq,qG,33,n,0);for(g=0;g<n;++g){o[g]=new tv;o[g].b=$doc.createElement(ZH);ys(b,o[g].b)}j=0;k=e-1;l=0;p=n-1;c=null;for(h=new py(a.f);h.a<h.b.c-1;){d=ny(h);i=vl(d.k,32);q=$doc.createElement($H);i.d=q;i.d[_H]=i.b;Bs(i.d,aI,i.e);i.d[VH]=i.f;i.d[UH]=i.c;if(i.a==av){As(o[l].b,q,o[l].a);ys(q,d.o);q[bI]=k-j+1;++l}else if(i.a==bv){As(o[p].b,q,o[p].a);ys(q,d.o);q[bI]=k-j+1;--p}else if(i.a==Yu){c=q}else if(kv(i.a)){m=o[l];As(m.b,q,m.a++);ys(q,d.o);q[cI]=p-l+1;++j}else if(lv(i.a)){m=o[l];As(m.b,q,m.a);ys(q,d.o);q[cI]=p-l+1;--k}}if(a.a){m=o[l];As(m.b,c,m.a);ys(c,a.a.o)}}
function mc(a){if(!a.a){a.a=true;qj();ef(nj,'*{margin:0;padding:0;}html{height:100%;}header,nav,section,article,aside,footer{display:block;}body{font:12px/ 18px Arial, Tahoma, Verdana, sans-serif;height:100%;}.GGPMPBCDKB{width:100%;min-width:1000px;min-height:100%;height:auto !important;height:100%;}.GGPMPBCDGB{height:150px;background:#ffe680;}.GGPMPBCDHB{width:100%;padding:0 0 100px;height:1%;position:relative;}.GGPMPBCDHB:after{content:".";display:block;clear:both;visibility:hidden;height:0;}.GGPMPBCDDB{width:100%;float:left;overflow:hidden;}.GGPMPBCDEB{padding:0 270px 0 270px;}.GGPMPBCDIB{float:left;width:250px;margin-left:-100%;position:relative;background:#b5e3ff;}.GGPMPBCDJB{float:left;margin-right:-3px;width:250px;margin-left:-250px;position:relative;background:#ffacaa;}.GGPMPBCDFB{margin-bottom:100px;background:#b0008e;}');sj();return true}return false}
function gc(a){if(!a.a){a.a=true;qj();ef(nj,'.GGPMPBCDC{background-color:#00f;height:100%;min-height:800px;}.GGPMPBCDD{padding-left:20px;}.GGPMPBCDF::-webkit-scrollbar-track{border:1px solid #6d0019;background-color:#f5f5f5;}.GGPMPBCDF::-webkit-scrollbar{width:10px;background-color:#f5f5f5;}.GGPMPBCDF::-webkit-scrollbar-thumb{background:#cc002c;background:-moz-linear-gradient(top, #cc002c 0, #6d0019 100%);background:-webkit-gradient(linear, left top, left bottom, color-stop(0, #cc002c), color-stop(100%, #6d0019));background:-webkit-linear-gradient(top, #cc002c 0, #6d0019 100%);background:-o-linear-gradient(top, #cc002c 0, #6d0019 100%);background:-ms-linear-gradient(top, #cc002c 0, #6d0019 100%);background:linear-gradient(top, #cc002c 0, #6d0019 100%);filter:progid;}.GGPMPBCDE{padding-left:50px;background:#f5edef;overflow-y:auto;overflow-x:hidden;}.GGPMPBCDB{font-weight:bold;font-family:arial, sans-serif;color:#3c3c3c;}.GGPMPBCDA{font-weight:bold;font-size:13px;font-family:arial, sans-serif;color:#000;}*{margin:0;padding:0;}html{height:100%;}header,nav,section,article,aside,footer{display:block;}body{font:12px/ 18px Arial, Tahoma, Verdana, sans-serif;height:100%;}');sj();return true}return false}
function jc(a){if(!a.a){a.a=true;qj();ef(nj,'.GGPMPBCDL{border-top-color:#ebebeb;border-top-style:solid;border-top-width:1px;bottom:0;height:35px;overflow:hidden;position:absolute;width:100%;margin:-50px auto 0 auto;}.GGPMPBCDN{border-top-color:#ebebeb;border-top-style:solid;border-top-width:1px;bottom:0;height:35px;overflow:hidden;position:absolute;width:100%;}.GGPMPBCDJ{border-top-color:#ff0;border-top-style:solid;border-top-width:1px;bottom:0;height:35px;position:absolute;margin:0;width:100%;}.GGPMPBCDK{font-size:0.85em;line-height:0;padding-top:9px;white-space:nowrap;}.GGPMPBCDM{clear:both;position:relative;z-index:10;height:3em;margin-top:-3em;}.GGPMPBCDP{background-color:#f00;}.GGPMPBCDAB{background-color:#f1f1f1;border-bottom-color:#ebebeb;border-bottom-style:solid;border-bottom-width:1px;}.GGPMPBCDBB{float:left;padding-top:15px;padding-bottom:15px;padding-left:25px;}.GGPMPBCDCB{float:right;right:0;padding-top:20px;padding-left:10px;}#footer{margin:-100px auto 0;min-width:1000px;height:100px;background:#bff08e;position:relative;}.GGPMPBCDO{background-color:#f1f1f1;}.GGPMPBCDG{margin:5 auto;background-color:#fff;padding:10px;}.GGPMPBCDI{background-color:#f1f1f1;border-top-color:#e0e0e0;border-top-style:solid;border-top-width:1px;bottom:0;}.GGPMPBCDH{min-height:100%;}');sj();return true}return false}
var XH='30px',bI='colSpan',cI='rowSpan';fr(18,5,iG,Jb);_.X=function Kb(){};_.Y=function Lb(){};_.Z=function Mb(){};_.$=function Nb(){};_._=function Ob(){iB();L(this,new kB(this))};fr(21,14,{},Xb);_.db=function Yb(){return this.a};_.a=null;fr(22,1,{},$b);fr(23,1,{},bc);_.a=null;_.b=null;_.c=null;_.d=null;_.e=null;var cc=null,dc=null,ec=null;fr(25,1,{},hc);_.a=false;fr(26,1,{},kc);_.a=false;fr(27,1,{},nc);_.a=false;fr(47,1,nG);_.gb=function ud(){Lz(this.b,ld(this.a.a))};fr(234,232,EG,mv);_.Cb=function nv(a){var b;b=uu(this,a);if(b){a==this.a&&(this.a=null);fv(this)}return b};_.a=null;var Yu,Zu,$u,_u,av,bv,cv;fr(235,1,{},pv);fr(236,1,{32:1},rv);_.a=null;_.c=RG;_.d=null;_.f=RG;fr(237,1,{33:1},tv);_.a=0;_.b=null;var Kl=FB(BH,'HomePresenter',18),Ql=FB(BH,'HomeView',21),Pl=FB(BH,'HomeView_BinderImpl',22),Ll=FB(BH,'HomeView_BinderImpl$Widgets',23),no=FB(fI,'DockPanel',234),mo=FB(fI,'DockPanel$TmpRow',237),Tq=EB(gI,'DockPanel$TmpRow;',380),ko=FB(fI,'DockPanel$DockLayoutConstant',235),lo=FB(fI,'DockPanel$LayoutData',236),Ml=FB(BH,'HomeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',25),Nl=FB(BH,'HomeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$2',26),Ol=FB(BH,'HomeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$3',27);OG(vf)(1);