function $b(){}
function hc(){}
function kc(){}
function nc(){}
function lw(){}
function pw(){}
function kd(a,b){a.X(b)}
function Su(a,b){Bt(a.p,aJ,b)}
function Uu(a,b){Bt(a.p,bJ,b)}
function hd(a,b){return new Jb(a,b)}
function Xb(){this.b=ac(new bc)}
function oc(){oc=gH;cc=new hc}
function pc(){pc=gH;dc=new kc}
function qc(){qc=gH;ec=new nc}
function Jb(a,b){Ib();Q.call(this,a,b)}
function At(a,b,c){su(a,($x(),_x(b)),c)}
function gw(a){if(a==Xv){return true}return a==$v}
function hw(a){if(a==Wv){return true}return a==Vv}
function nw(a){this.c=(ax(),Zw).b;this.f=(fx(),ex).b;this.b=a}
function iw(){_v();Pv.call(this);this.c=(ax(),Zw);this.d=(fx(),ex);this.f[lJ]=0;this.f[mJ]=0}
function cw(a,b){var c;c=qm(a.n,33);c.d=b;!!c.e&&Bt(c.e,aJ,c.d)}
function fw(a,b){var c;c=qm(a.n,33);c.g=b;!!c.e&&Bt(c.e,bJ,c.g)}
function ew(a,b){var c;c=qm(a.n,33);c.f=b.b;!!c.e&&Bt(c.e,iJ,b.b)}
function dw(a,b){var c;c=qm(a.n,33);c.c=b.b;!!c.e&&(c.e[hJ]=b.b,undefined)}
function qu(a){var b=0,c=a.firstChild;while(c){c.nodeType==1&&++b;c=c.nextSibling}return b}
function pu(a,b){var c=0,d=a.firstChild;while(d){if(d.nodeType==1){if(b==c)return d;++c}d=d.nextSibling}return null}
function su(a,b,c){var d=0,e=a.firstChild,f=null;while(e){if(e.nodeType==1){if(d==c){f=e;break}++d}e=e.nextSibling}a.insertBefore(b,f)}
function _v(){_v=gH;Uv=new lw;Xv=new lw;Wv=new lw;Vv=new lw;Yv=new lw;Zv=new lw;$v=new lw}
function qd(a){var b;!a.f&&(a.f=(b=hd((!a.n&&(a.n=new Jl),a.n),(!a.g&&(a.g=new Xb(new $b)),a.g),!a.e&&(a.e=new Qb)),kd(b,(!a.p&&(a.p=new Iz),a.p)),b));return a.f}
function aw(a,b,c){var d;if(c==Uv){if(b==a.b){return}else if(a.b){throw new NC('Only one CENTER widget may be added')}}cv(b);cz(a.g,b);c==Uv&&(a.b=b);d=new nw(c);b.n=d;dw(b,a.c);ew(b,a.d);bw(a);ev(b,a)}
function ac(a){var b,c,d;b=new iw;aw(b,(c=new Xw((d=new ED,new Ns(d.b.b)).b),c.p[_I]='GJ-33NUDJ',c.p.style[aJ]='70px',c.p.style[bJ]=cJ,c),(_v(),Yv));aw(b,a.c,Uv);fw(a.c,cJ);cw(a.c,cJ);aw(b,a.d,Zv);fw(a.d,cJ);cw(a.d,dJ);aw(b,a.e,$v);fw(a.e,eJ);cw(a.e,cJ);b.p[_I]='GJ-33NUMI';b.p.style[aJ]=cJ;b.p.style[bJ]=cJ;return b}
function bc(){var a,b,c,d;a=(qc(),ec);mc(a);this.b=(oc(),cc);gc(this.b);this.f=(pc(),dc);jc(this.f);this.c=new Xw((b=new ED,new Ns(b.b.b)).b);Tu(this.c,'GJ-33NULI');Su(this.c,cJ);Uu(this.c,cJ);this.d=new Xw((c=new ED,new Ns(c.b.b)).b);Tu(this.d,'GJ-33NUNI');Su(this.d,dJ);Uu(this.d,cJ);this.e=new Xw((d=new ED,new Ns(d.b.b)).b);Tu(this.e,'GJ-33NUJI GJ-33NUKI');Su(this.e,cJ);Uu(this.e,'200px')}
function bw(a){var b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q;b=a.e;while(qu(b)>0){Kh(b,pu(b,0))}n=1;e=1;for(h=new mz(a.g);h.b<h.c.d-1;){d=kz(h);f=qm(d.n,33).b;f==Yv||f==Zv?++n:(f==Vv||f==$v||f==Xv||f==Wv)&&++e}o=gm(Yr,tH,34,n,0);for(g=0;g<n;++g){o[g]=new pw;o[g].c=$doc.createElement(fJ);yt(b,o[g].c)}j=0;k=e-1;l=0;p=n-1;c=null;for(h=new mz(a.g);h.b<h.c.d-1;){d=kz(h);i=qm(d.n,33);q=$doc.createElement(gJ);i.e=q;i.e[hJ]=i.c;Bt(i.e,iJ,i.f);i.e[bJ]=i.g;i.e[aJ]=i.d;if(i.b==Yv){At(o[l].c,q,o[l].b);yt(q,d.p);q[jJ]=k-j+1;++l}else if(i.b==Zv){At(o[p].c,q,o[p].b);yt(q,d.p);q[jJ]=k-j+1;--p}else if(i.b==Uv){c=q}else if(gw(i.b)){m=o[l];At(m.c,q,m.b++);yt(q,d.p);q[kJ]=p-l+1;++j}else if(hw(i.b)){m=o[l];At(m.c,q,m.b);yt(q,d.p);q[kJ]=p-l+1;--k}}if(a.b){m=o[l];At(m.c,c,m.b);yt(c,a.b.p)}}
function mc(a){if(!a.b){a.b=true;ck();xf(_j,'*{margin:0;padding:0;}html{height:100%;}header,nav,section,article,aside,footer{display:block;}body{font:12px/ 18px Arial, Tahoma, Verdana, sans-serif;height:100%;}.GJ-33NUPJ{width:100%;min-width:1000px;min-height:100%;height:auto !important;height:100%;}.GJ-33NULJ{height:150px;background:#ffe680;}.GJ-33NUMJ{width:100%;padding:0 0 100px;height:1%;position:relative;}.GJ-33NUMJ:after{content:".";display:block;clear:both;visibility:hidden;height:0;}.GJ-33NUIJ{width:100%;float:left;overflow:hidden;}.GJ-33NUJJ{padding:0 270px 0 270px;}.GJ-33NUNJ{float:left;width:250px;margin-left:-100%;position:relative;background:#b5e3ff;}.GJ-33NUOJ{float:left;margin-right:-3px;width:250px;margin-left:-250px;position:relative;background:#ffacaa;}.GJ-33NUKJ{margin-bottom:100px;background:#b0008e;}');ek();return true}return false}
function gc(a){if(!a.b){a.b=true;ck();xf(_j,'.GJ-33NUHI{background-color:#00f;height:100%;min-height:800px;}.GJ-33NUII{padding-left:20px;}.GJ-33NUKI::-webkit-scrollbar-track{border:1px solid #6d0019;background-color:#f5f5f5;}.GJ-33NUKI::-webkit-scrollbar{width:10px;background-color:#f5f5f5;}.GJ-33NUKI::-webkit-scrollbar-thumb{background:#cc002c;background:-moz-linear-gradient(top, #cc002c 0, #6d0019 100%);background:-webkit-gradient(linear, left top, left bottom, color-stop(0, #cc002c), color-stop(100%, #6d0019));background:-webkit-linear-gradient(top, #cc002c 0, #6d0019 100%);background:-o-linear-gradient(top, #cc002c 0, #6d0019 100%);background:-ms-linear-gradient(top, #cc002c 0, #6d0019 100%);background:linear-gradient(top, #cc002c 0, #6d0019 100%);filter:progid;}.GJ-33NUJI{padding-left:50px;background:#f5edef;overflow-y:auto;overflow-x:hidden;}.GJ-33NUGI{font-weight:bold;font-family:arial, sans-serif;color:#3c3c3c;}.GJ-33NUFI{font-weight:bold;font-size:13px;font-family:arial, sans-serif;color:#000;}*{margin:0;padding:0;}html{height:100%;}header,nav,section,article,aside,footer{display:block;}body{font:12px/ 18px Arial, Tahoma, Verdana, sans-serif;height:100%;}');ek();return true}return false}
function jc(a){if(!a.b){a.b=true;ck();xf(_j,'.GJ-33NUAJ{border-top-color:#ebebeb;border-top-style:solid;border-top-width:1px;bottom:0;height:35px;overflow:hidden;position:absolute;width:100%;margin:-50px auto 0 auto;}.GJ-33NUCJ{border-top-color:#ebebeb;border-top-style:solid;border-top-width:1px;bottom:0;height:35px;overflow:hidden;position:absolute;width:100%;}.GJ-33NUOI{border-top-color:#ff0;border-top-style:solid;border-top-width:1px;bottom:0;height:35px;position:absolute;margin:0;width:100%;}.GJ-33NUPI{font-size:0.85em;line-height:0;padding-top:9px;white-space:nowrap;}.GJ-33NUBJ{clear:both;position:relative;z-index:10;height:3em;margin-top:-3em;}.GJ-33NUEJ{background-color:#f00;}.GJ-33NUFJ{background-color:#f1f1f1;border-bottom-color:#ebebeb;border-bottom-style:solid;border-bottom-width:1px;}.GJ-33NUGJ{float:left;padding-top:15px;padding-bottom:15px;padding-left:25px;}.GJ-33NUHJ{float:right;right:0;padding-top:20px;padding-left:10px;}#footer{margin:-100px auto 0;min-width:1000px;height:100px;background:#bff08e;position:relative;}.GJ-33NUDJ{background-color:#f1f1f1;}.GJ-33NULI{margin:5 auto;background-color:#fff;padding:10px;}.GJ-33NUNI{background-color:#f1f1f1;border-top-color:#e0e0e0;border-top-style:solid;border-top-width:1px;bottom:0;}.GJ-33NUMI{min-height:100%;}');ek();return true}return false}
var dJ='30px',jJ='colSpan',kJ='rowSpan';ks(18,5,kH,Jb);_.Y=function Kb(){};_.Z=function Lb(){};_.$=function Mb(){};_._=function Nb(){};_.ab=function Ob(){fC();L(this,new hC(this))};ks(21,14,{},Xb);_.eb=function Yb(){return this.b};_.b=null;ks(22,1,{},$b);ks(23,1,{},bc);_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;var cc=null,dc=null,ec=null;ks(25,1,{},hc);_.b=false;ks(26,1,{},kc);_.b=false;ks(27,1,{},nc);_.b=false;ks(50,1,pH);_.hb=function zd(){IA(this.c,qd(this.b.b))};ks(235,233,HH,iw);_.Kb=function jw(a){var b;b=pv(this,a);if(b){a==this.b&&(this.b=null);bw(this)}return b};_.b=null;var Uv,Vv,Wv,Xv,Yv,Zv,$v;ks(236,1,{},lw);ks(237,1,{33:1},nw);_.b=null;_.d=VH;_.e=null;_.g=VH;ks(238,1,{34:1},pw);_.b=0;_.c=null;var Fm=DC(JI,'HomePresenter',18),Lm=DC(JI,'HomeView',21),Km=DC(JI,'HomeView_BinderImpl',22),Gm=DC(JI,'HomeView_BinderImpl$Widgets',23),rp=DC(nJ,'DockPanel',235),qp=DC(nJ,'DockPanel$TmpRow',238),Yr=CC(oJ,'DockPanel$TmpRow;',382),op=DC(nJ,'DockPanel$DockLayoutConstant',236),pp=DC(nJ,'DockPanel$LayoutData',237),Hm=DC(JI,'HomeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',25),Im=DC(JI,'HomeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$2',26),Jm=DC(JI,'HomeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$3',27);RH(Nf)(1);