// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package au.com.showcase.application.client.bundle;

import com.google.gwt.resources.client.CssResource;

public interface CustomWidget extends CssResource {

	String textBoxError();

	String errorInfoBubble();

	String textboxFirstNameError();

	String textboxLastNameError();

}