// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package au.com.showcase.application.client.bundle;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface RegistrationForm extends CssResource {
  
  String agreement();
  
  String bodyLayout();
  
  String content1();
  
  String dropdown();
  
  @ClassName("dropdown-dark")
  String dropdownDark();
  
  @ClassName("dropdown-select")
  String dropdownSelect();
  
  String errorInfoBubble();
  
  String errorMsgHide();
  
  String errorMsgShow();
  
  String formLayout();
  
  @ClassName("gwt-CheckBox")
  String gwtCheckBox();
  
  @ClassName("gwt-RadioButton")
  String gwtRadioButton();
  
  String horiCon();
  
  String label();
  
  String labelAgreement();
  
  String loginTextBox();
  
  @ClassName("lt-ie9")
  String ltIe9();
  
  String rightAlign();
  
  String rowDate();
  
  @ClassName("select-style")
  String selectStyle();
  
  @ClassName("select-styleGender")
  String selectStyleGender();
  
  String select1();
  
  String submit();
  
  String textbox();
  
  String textboxCaptchaImage();
  
  String textboxCaptchaText();
  
  String textboxChooseUserName();
  
  String textboxDate();
  
  String textboxEmailAddress();
  
  String textBoxError();
  
  String textboxFirstName();
  
  String textboxFirstNameError();
  
  String textboxLastName();
  
  String textboxLastNameError();
  
  String textboxMobileNumber();
  
  String verti();
}

